FROM php:7.2-fpm-alpine

# Install php extensions
RUN docker-php-ext-install pdo pdo_mysql

COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'